from enum import Enum


class ErrorCode(str, Enum):
    AUTH_FAILED     = "AUTH_FAILED"
    USER_EXISTS     = "USER_EXISTS"
    USER_NOT_FOUND  = "USER_NOT_FOUND"
    INVALID_TOKEN   = "INVALID_TOKEN"
    RATE_LIMITED    = "RATE_LIMITED"
    INVALID_PACKET  = "INVALID_PACKET"
    UNAUTHORIZED    = "UNAUTHORIZED"


MAX_MESSAGE_LEN    = 4096
MAX_USERNAME_LEN   = 32
MIN_PASSWORD_LEN   = 8
SESSION_TTL        = 86400 * 7   # 7 days in seconds
OFFLINE_QUEUE_TTL  = 86400 * 30  # 30 days
